name: Log GitHub Traffic

on:
  schedule:
    - cron: "0 0 * * *"  # Every day at midnight UTC
  workflow_dispatch:

jobs:
  log-traffic:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up GitHub CLI
        run: sudo apt install gh -y

      - name: Debug raw traffic API output
        env:
          GH_TOKEN: ${{ secrets.GH_TRAFFIC_TOKEN }}
          REPO: jodithea/Polygenic_score_workshop
        run: |
          echo "== Views JSON =="
          gh api repos/$REPO/traffic/views
          echo
          echo "== Clones JSON =="
          gh api repos/$REPO/traffic/clones

      - name: Fetch and log traffic data
        env:
          GH_TOKEN: ${{ secrets.GH_TRAFFIC_TOKEN }}
          REPO: jodithea/Polygenic_score_workshop
        run: |
          TRAFFIC_FILE="traffic_log.csv"
          TEMP_FILE="traffic_temp.csv"
          MERGED_FILE="merged.csv"

          # Create CSV file with header if it doesn't exist
          if [ ! -f "$TRAFFIC_FILE" ]; then
            echo "timestamp,type,count,uniques" > "$TRAFFIC_FILE"
          fi

          # Fetch new traffic data into TEMP_FILE
          gh api repos/$REPO/traffic/views --jq '.views[] | "\(.timestamp),views,\(.count),\(.uniques)"' > "$TEMP_FILE"
          gh api repos/$REPO/traffic/clones --jq '.clones[] | "\(.timestamp),clones,\(.count),\(.uniques)"' >> "$TEMP_FILE"

          # Merge, deduplicate, and sort data by timestamp (skip old summaries and headers)
          {
            grep -vE '^(summary|timestamp)' "$TRAFFIC_FILE"
            cat "$TEMP_FILE"
          } | awk -F, '{
            key = $1","$2;
            data[key] = $0;
          }
          END {
            for (k in data) print data[k]
          }' | sort -t, -k1,1 > "$MERGED_FILE"

          # Calculate running totals
          VIEWS_TOTAL=$(grep ',views,' "$MERGED_FILE" | awk -F, '{c+=$3; u+=$4} END {print c","u}')
          CLONES_TOTAL=$(grep ',clones,' "$MERGED_FILE" | awk -F, '{c+=$3; u+=$4} END {print c","u}')

          # Final CSV: summaries at top, sorted data, footer header
          {
            echo "summary,views,$VIEWS_TOTAL"
            echo "summary,clones,$CLONES_TOTAL"
            echo "timestamp,type,count,uniques"
            cat "$MERGED_FILE"
            echo "timestamp,type,count,uniques"
          } > "$TRAFFIC_FILE"

          # Commit and push if changes
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add "$TRAFFIC_FILE"
          git commit -m "Log GitHub traffic: $(date -u +"%Y-%m-%dT%H:%M:%SZ")" || echo "No changes to commit"
          git push
