name: Log GitHub Traffic

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  log-traffic:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up GitHub CLI
        run: sudo apt install gh -y

      - name: Fetch and log traffic data
        env:
          GH_TOKEN: ${{ secrets.GH_TRAFFIC_TOKEN }}
          REPO: jodithea/Polygenic_score_workshop
        run: |
          TRAFFIC_FILE="traffic_log.csv"
          TEMP_FILE="traffic_temp.csv"
          MERGED_FILE="merged.csv"

          # Ensure CSV exists
          if [ ! -f "$TRAFFIC_FILE" ]; then
            echo "timestamp,type,count,uniques" > "$TRAFFIC_FILE"
          fi

          # Fetch latest daily views and clones using GH_TOKEN directly
          gh api repos/$REPO/traffic/views --jq '.views[] | "\(.timestamp),views,\(.count),\(.uniques)"' >> "$TEMP_FILE"
          gh api repos/$REPO/traffic/clones --jq '.clones[] | "\(.timestamp),clones,\(.count),\(.uniques)"' >> "$TEMP_FILE"

          # Merge and deduplicate
          cat "$TEMP_FILE" "$TRAFFIC_FILE" | grep -v '^summary' | sort -u > "$MERGED_FILE"

          # Compute running totals
          VIEWS_TOTAL=$(grep ',views,' "$MERGED_FILE" | awk -F, '{c+=$3; u+=$4} END {print c","u}')
          CLONES_TOTAL=$(grep ',clones,' "$MERGED_FILE" | awk -F, '{c+=$3; u+=$4} END {print c","u}')

          # Write summary + header + logs
          {
            echo "summary,views,$VIEWS_TOTAL"
            echo "summary,clones,$CLONES_TOTAL"
            echo "timestamp,type,count,uniques"
            grep -v '^summary' "$MERGED_FILE"
          } > "$TRAFFIC_FILE"

          # Commit if there are changes
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add "$TRAFFIC_FILE"
          git commit -m "Log GitHub traffic: $(date -u +"%Y-%m-%dT%H:%M:%SZ")" || echo "No changes to commit"
          git push
