name: Log GitHub Traffic

on:
  schedule:
    - cron: "0 0 * * *"  # Every day at midnight UTC
  workflow_dispatch:

jobs:
  log-traffic:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug Views JSON
        env:
          GH_TOKEN: ${{ secrets.GH_TRAFFIC_TOKEN }}
          REPO: jodithea/Polygenic_score_workshop
        run: |
          curl -s -H "Authorization: token $GH_TOKEN" https://api.github.com/repos/$REPO/traffic/views

      - name: Debug Clones JSON
        env:
          GH_TOKEN: ${{ secrets.GH_TRAFFIC_TOKEN }}
          REPO: jodithea/Polygenic_score_workshop
        run: |
          curl -s -H "Authorization: token $GH_TOKEN" https://api.github.com/repos/$REPO/traffic/clones

      - name: Log traffic stats (views + clones)
        env:
          GH_TOKEN: GH_TOKEN: ${{ secrets.GH_TRAFFIC_TOKEN }}
          REPO: jodithea/Polygenic_score_workshop
        run: |
          DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          TRAFFIC_FILE="traffic_log.csv"
